export const REPORT = {
  fr: {
    title: "Estimation Build Block",
    quantities: "Blocs",
    blocks: {
      straight: "Bloc droit",
      ninetyCorner: "Coin à 90 degrés",
      fortyFiveCorner: "Coin à 45 degrés",
      brickLedge: "Support à maçon",
      doubleTaperTop: "Double biseau",
      buck: "Buck",
      thermalsert: "Insertion isolante",
      kdStraight: "Déconstruit droit",
      kdNinetyCorner: "Déconstruit coin à 90 degrés",
      kdBrickLedge: "Déconstruit support à maçon",
      kdDoubleTaperTop: "Déconstruit double biseau",
    },
    units: "unités",
    bundles: "paquets",
    totalQuantity: "Quantité",
    concreteVolume: "Volume de ciment (net)",
    terms: `
        TERMES ET CONDITIONS
*   Cette estimation budgétaire est offerte à titre informatif seulement et Styrorail inc. ne peut être tenu responsable de l'exactitude de cette estimation, tant au niveau du matériel BuildBlock que de la quantité de béton ou d'armatures requises ou tout autres items additionnels. Nous vous recommandons de faire analyser les quantitées par l'entrepreneur au projet.
**  Les produits sont expédiés uniquement par lots. Aucun retour accepté.`,
    rebars: "Barres d'armature d'acier (20')",
    clips: "Clips",
    bridges: "Bridges",
    additionalInformation: "Informations supplémentaires",
    grossSquareFootage: "Surface (brute)",
    netSquareFootage: "Surface (nette)",
    openingSquareFootage: "Surface d'ouverture",
  },
  eng: {
    title: "Build Block Estimate",
    quantities: "Blocks",
    blocks: {
      straight: "Straight block",
      ninetyCorner: "90-degree corner",
      fortyFiveCorner: "45-degree corner",
      brickLedge: "Brick ledge",
      doubleTaperTop: "Double taper",
      thermalsert: "Insulating insert",
      buck: "Buck",
      kdStraight: "Knockdown straight",
      kdNinetyCorner: "Knockdown 90-degree corner",
      kdBrickLedge: "Knockdown brickledge",
      kdDoubleTaperTop: "Knockdown double taper",
    },
    units: "units",
    bundles: "bundles",
    totalQuantity: "Total quantity",
    concreteVolume: "Concrete volume (net)",
    terms: `
    TERMS AND CONDITIONS
*   This budget estimate is provided for informational purposes only and Styrorail inc. can not be held responsible for the accuracy of this estimate, both in terms of SR.Block material, the concrete quantity or reinforcement required or any other additional items.
**  Products are shipped only by bundles. No return accepted.`,
    rebars: "Steel reinforcement bars (20')",
    clips: "Clips",
    bridges: "Bridges",
    additionalInformation: "Additional Information",
    grossSquareFootage: "Square footage (gross)",
    netSquareFootage: "Square footage (net)",
    openingSquareFootage: "Opening square footage",
  },
};
